swagger/model_builder.go, swagger/model_builder_test.go, swagger/swagger.go, swagger/swagger_test.go
According to the documentation https://github.com/swagger-api/swagger-spec/blob/master/versions/1.2.md#434-items-object Items field should be object, not an array.
Also this PR fixes bug with slices, because []Address is equal []*Address in swagger representation
=> Swagger items should be object

route.go, route_builder.go, swagger/swagger_webservice.go
It's very often required to add extra information about api endpoint. According to the swagger spec [0] Notes field is a verbose explanation of the operation behavior.
[0] https://github.com/swagger-api/swagger-spec/blob/master/versions/1.2.md#523-operation-object
=> Add useful Notes method for swagger

README.md, container.go
Adds `ServiceErrorHandler` to allow custom rendering of ServiceError objects. This is useful when a server wants 404/405/406/415 errors to be rendered in a specific way consumable by API clients, rather than just as status codes and plain text messages.
=> Allow customizing rendering of ServiceErrors

examples/restful-routefunction_test.go
Logf output is only shown on test failure. With this change, the unit test now fails, and I'm not sure why.
=> In routefunction_test, use Fatalf instead of Logf.

logger.go
As easy as that. Not really sure how to test this, I guess the type checker does that for us.
I did a quick test with log.Logger and logrus.logger and both work, tests pass as well.
closes #187
=> Use an interface for Logger instead of concrete type

container.go, doc.go, log/log.go, logger.go, route_builder.go, swagger/swagger_webservice.go, web_service.go
closes #189 
The TraceLogger is still there and seperate because I tried not to break anything, but perhaps 
it would have been better to simply enable/disable it instead and use the same package-wide logger.
=> Add 'log' package for package-wide logging, expose SetLogger(Logger).

container.go, cors_filter.go, log/log.go, route_builder.go, web_service.go
After trying yet another logging package (each has its warts) I think it would have been
better If I had opted for the most minimal Interface possible in #188, to support other loggers most easily. In addition, most of the called are rather superfluous
- The `log.Fatal*` variant is just a `Print*` + `os.Exit`, just as Panic* is a  `Print*` + Panic`. Easy to manually insert this where need in the package (as I've done here).
- The `log.Println` variant is semi-useless. `godoc fmt` says:
```
variant Println inserts blanks between operands and appends a newline.
```   
Well, The newline is irrelevent because that's handled by the log package and not by the caller. The blanks are easily inserted explicitly when there are multiple arguments. To illustrate:
```go
log.Print("foo", "bar") …
```
=> Reduce StdLogger interface to bare minimum

route.go, route_test.go
This PR fix to match any mime types when Route produce "\*/\*" (such as proxy).
```go
proxyRoute := ws.Method(method).Path(path).To(routeFunction(proxyHandler)).
Filter(monitorFilter("PROXY", resource)).
Doc("proxy " + method + " requests to " + kind).
Operation("proxy" + method + kind).
Produces("*/*").
Consumes("*/*")
addParams(proxyRoute, params)
ws.Route(proxyRoute)
```
https://github.com/GoogleCloudPlatform/kubernetes/blob/cfb6f1199bae1c0c7968c7322dd1f0037624236c/pkg/apiserver/api_installer.go#L638
```
% curl -H "Accept: application/json" https://example.com/...
// 406: Not Acceptable
```
=> Fix to match any mime types when Route produce "*/*"

swagger/model_builder.go, swagger/model_builder_test.go
A nested embedded struct (embedded in Golang, nested in JSON) is possible by
default. The inline tag forces a struct to be included by default. This
commit adds that check.
@bgrant0607 FYI we need this for v1beta3 metadata
=> Embedded structs can have a JSON tag for nesting

swagger/model_builder.go, swagger/model_builder_test.go
If embeded(inlined) model has complex fields (like array of struct) then model builder should add all sub references.
=> Add all sub ref models for inline field

swagger/model_builder.go, swagger/model_property_ext_test.go
Add another field tag "modelDescription", which can be specified in 
In addModel(), contents in modelDescription tags are aggregated and populate to Model.Description
#212
@emicklei @bgrant0607
=> add modelDesription tag to populate Model.Description

swagger/README.md, swagger/model_builder.go, swagger/model_builder_test.go
In [GoogleCloudPlatform/kubernetes](https://github.com/GoogleCloudPlatform/kubernetes) we are using Swagger to describe all of our types.
The problem that we are facing with the current way of describing our models is that we have to keep field and struct documentation in two different places (1) as comments 2) as struct tags so go-restful can parse). You can see [here](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/v1/types.go#L82) an example.
We think that it is easier for us to attach a method on each struct so go-restful can get the description from those methods instead of struct tags. We have a way to automatically parse the documentation from the source code and then create methods for each of our structs to contain the comments.
=> Models can generate documentation through a struct method

container.go, web_service_test.go
Since the `CompressingResponseWriter` is closed before calling panic handler, every response that panic handler make will not be sent to client. This PR fixes the situation.
Also I've added a test for this situation. The test will fail with previous code.
Thank you!
=> Paniced responses not sent with Container.EnableContentEncoding(true)

swagger/model_builder.go, swagger/model_builder_test.go
Description was missing if a pointer field was present.
=> Fixed missing ptr description

swagger/model_builder.go, swagger/model_builder_test.go
Hello, my previous commit 712d410a5f8fec68f2bce34d006a6c20c4538d88 on using descriptions from methods is not working properly.
Last time we discussed on #215 moving description parsing after `PostBuildModel`. That was a good idea but it is not enough. When we have to deal with nested models using `PostBuildModel` is making things much more complicated and also there are cases that swagger is defining models without calling `PostBuildModel` afterwords [here](https://github.com/emicklei/go-restful/blob/master/swagger/swagger_webservice.go#L258).
=> fix description parsing on recursion

response.go
With this feature, people can create a filter that log all errors
without the use of req.Attribute (which may cause uggy code).
It is extremely useful when the error passed into response is a self
define error, for example:
```go
type myError struct {
exported string
detailed string
}
// write to client side
func (m myError) Error() string { return m.exported }
// write to server log
func (m myError) Detailed() string { return m.detailed }
func ErrorLogFilter(req *restful.Request, resp *restful.Response, chain
*restful.Chain) {
chain.Process(req, resp)
if err := resp.Error(); err != nil {
if e, ok := err.(myError); ok {
// log
}
}
}
```
=> refs #220, save error for future use when resp.WriteError is called

parameter.go, swagger/swagger_webservice.go
Adds format to Parameter in go-restful and use it for the Format in Swagger UI.
This will fix issues such as the need to have dataType: "string" and dataFormat: "date-time"
https://github.com/swagger-api/swagger-spec/blob/master/versions/1.2.md#431-primitives
I made it "backwards compatible" as I'm not sure what the original plan was for the //TODO in asFormat()
Change-Id: I29bed78705e42a4c09c0bb85c08f0d232b1b40d0
=> Adds format to Parameter in go-restful for use in Swagger UI

swagger/swagger.go, swagger/swagger_test.go, swagger/swagger_webservice.go, swagger/test_package/struct.go, swagger/utils_test.go
This allows you to specify an array in Writes(). (related to #228)
It looks like the spec doesn't support arrays in "responses" because they have to use a "responseModel" which is a string reference to a model. A model can't be an array AFAIK.
This is a good compromise because in most cases Writes() is sufficient for expressing the return type of an API.
I might not have written this patch in the best way possible, so feel free to completely rewrite it. I also didn't see an easy way to test the output, but at least I made sure that the code gets executed in a test case.
=> fix bug with arrays in Writes() not parsed by swagger #228

swagger/swagger_webservice.go
Hi,
there was a smuggled fmt.Println method call in one of previous pull-requests, probably used for debugging. I removed this call.
=> Removed left fmt.Println method in SwaggerService

swagger/model_builder.go, swagger/model_builder_test.go, swagger/model_property_ext.go, swagger/model_property_ext_test.go
This adds a "type" struct tag that can override the type guessed by reflection. I have updated the unit tests with some examples of where this might be useful, as an example a net.IP type and an int type alias. net.IP is itself a type alias for []byte, but it implements encoding.TextUnmarshaler and encoding.TextMarshaler to allow it to be represented as a string or converted from a string.
By the way, sorry for the closed then new PR's.  I didn't realize that if you close a PR, then rebase and force push, it wouldn't let you reopen.
=> Adding 'type' struct tag that can override the guessed type

compressor_pools.go
Hi Ernest,
I was curious about why do not put back resources to the compressor pool? Please review changes and have a nice day.
Best regards,
Marcin
=> Put acquired resources back to compressor pool

response.go
Come across this when tried to flush buffered data to client.  If this is not a wanted feature, do we have a better way to achieve the goal?
=> Add Flush method to response

cors_filter.go
I initialize services and containers like below:
```
// Register all rest endpoints.
ws := &restful.WebService{}
ws.Path(fmt.Sprintf("/api/%s", api.APIVersion)).
Consumes(restful.MIME_JSON).
Produces(restful.MIME_JSON)
registerAPIs(ws)
restful.Add(ws)
// Add container filter to enable CORS and respond to OPTIONS.
cors := restful.CrossOriginResourceSharing{
ExposeHeaders:  []string{"X-My-Header"},
AllowedHeaders: []string{"Content-Type"},
CookiesAllowed: false,
}
restful.Filter(cors.Filter)
restful.Filter(restful.OPTIONSFilter())
```
When receiving request, it gives me an invalid memory access error.  Since we already assumes DefaultContainer in quite a few place, it makes sense to also assume default container here as well.  
doPreflightRequest is the only place that accesses c.Container, …
=> cors filter to use default container

compress.go
When using a single `Container` that included routes for websockets it was discovered that setting `EnableContentEncoding(true)` was causing an error with gorilla's `websocket.Upgrader` as the `CompressingResponseWriter` does not implement the `http.Hijacker` interface.  This change adds a simple Hijack implementation that allows for the use of websocket endpoints within a `Container` when `EnableContentEncoding(true)` is set.
=> Implement http.Hijacker interface on CompressingResponseWriter

examples/google_app_engine/datastore/main.go, examples/google_app_engine/restful-user-service.go
Some examples referenced google.golang.com instead of google.golang.org
=> fix some example import paths

swagger/model_builder.go
As per https://github.com/kubernetes/kubernetes/issues/4700#issuecomment-194719759
=> Use type "object" instead of type "any" to represent unstructured objects

web_service.go, web_service_test.go
Solves the issue during a call to remove the last route of the webservice
```
E0410 07:26:58.832374       1 runtime.go:58] Recovered from panic: "index out of range" (runtime error: index out of range)
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/runtime/runtime.go:52
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/runtime/runtime.go:40
/usr/local/go/src/runtime/asm_amd64.s:472
/usr/local/go/src/runtime/panic.go:426
/usr/local/go/src/runtime/panic.go:15
/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/web_service.go:16
```
This solves the issue of IndexOutOfBounds from https://github.com/emicklei/go-restful/blob/master/web_service.go#L164
=> Fixing panic during remove route of last route in webservice

examples/msgpack/msgpack_entity.go, examples/msgpack/msgpack_entity_test.go
i have moved the msg pack to example folder,
but i don't know the const MIME_MSGPACK = "application/x-msgpack" place in here is OK?
=> Move msgpack to example

web_service.go
@emicklei ptal.
This will change `Path("") --> compilePathExpression() --> Path("/") --> compilePathExpression()` to `Path("") --> compilePathExpression()`
=> fix compile path twice issue

examples/restful-curly-router_test.go
The package for examples/restful-curly-router_test.go file was set to examples, instead of main like the rest of the files in that directory, which was breaking gb vendoring.
=> wrong package breaks vendoring (gb)

route_builder.go
=> Fixing typo in Operation receiver method documentation

swagger/config.go, swagger/model_builder.go, swagger/model_builder_test.go, swagger/swagger_webservice.go, swagger/utils_test.go
For a type that is marshaled manually, we do not have a way to specify its format. For example if we have a custom_time type that does not provided a custom marshaling, its swagger type would be string and its swagger format would be empty. The correct swagger format in this example is "date-time". This PR adds a function that maps type-name to swagger-format-field. If the function exists in swagger.Config and returns non-empty strings, that value will be used instead of internal model-builder map. #296
=> Customizable typename-to-swagger-format-field map

swagger/swagger_webservice.go
Swagger config should be passed to ModelBuilder when available. composeResponseMessages creates a model builder without swagger config. This is a missing peace for #297 (missed in last PR)
=> Bugfix: Swagger config is not propagated properly.

swagger/swagger.go
Allows post processing of ApiDecl to set the info field for swagger 1.0
(to add things like descriptions of APIs).
=> Add "Info" to go-restful ApiDecl

swagger/model_builder.go, swagger/model_builder_test.go
=> swagger: report golang type []byte as json type string

swagger/model_property_ext.go, swagger/model_property_ext_test.go
This pull request was born whilst using a custom type as a slice in a model struct.
The custom type `bson.ObjectId` implements correct marshaling, however when used as a slice/array in a model it does not reflect the type correctly in swagger documentation.
In the swagger docs `[]bson.ObjectId` becomes `[{}]` when it should reflect as `["string"]`
This PR allows you to use `[]` with the `type` tag to override custom types as slices/arrays instead of just basic types.
e.g `type:"[]string"` will result in `["string"]` for your model documentation.
=> Adding slice/array functionality to 'type' struct tag.

swagger/model_builder.go, swagger/model_builder_test.go
From a model perspective we treat `type.Struct` and `*type.Struct`
identically when nested, but if `*type.Struct` is passed to go-restful
via `.Writes()`. Since these are expected to be models, this is more
friendly to integrators.
Added test of passing a struct by pointer.
=> Accept pointers passed to model builder for swagger

swagger/config.go, swagger/model_builder.go, swagger/model_builder_test.go
As schemas become more complicated, the odds of two types in different
packages sharing the same generated "reflect.Type#String()" value
increases (e.g. `pkg/type/v1.Event` and `pkg/history/v1.Event` will both
result in `v1.Event` as a model name). This adds a new optional function
on the swagger.Config that can remap type names before they are written
into the Swagger model. Because types must be referenced across
structures, the mapping needs to happen at all the places that convert
`reflect.Type` to `string`.
Spawned by kubernetes/kubernetes#38071 where we now have duplicate type names.
@mbohlool this will allow us to bypass this problem in the short term.
=> Support renaming model type names holistically

route_builder.go, web_service.go, web_service_test.go
The only DataType value set outside of the swagger model builder is the
result of calling `.Reads(...)` on a Route. In order to allow someone to
properly generate a consistent Swagger doc where the default
`reflect.TypeOf().String()` call would not be unique across an API for
multiple types, add a new method to WebService to allow the caller to
define their own pattern for this.
This is a continuation of #325 and closes a gap I missed in that PR.  I tried to keep this minimal by making an optional flag added to WebService - was hoping originally to inherit from container but since WebServices are instantiated by callers and data type is resolved prior to being added to a container there was no way to accomplish that.
=> Allow body parameter type name to be customized

swagger/swagger_test.go, swagger/swagger_webservice.go, swagger/utils_test.go
Hi,
I have defined two webservices:
/foobar
/foo
Each of them has defined GET and HEAD routes. When listing swagger API declarations, endpoints corresponding to /foo are also listed under /foobar.
Fix checks if there are compared entire paths instead of sudden exact substrings.
Please review the pull request.
Kind regards,
Marcin
=> Fix invalid compared Swagger paths

route.go, route_builder.go, route_builder_test.go
The PR allows storing metadata with each route. This metadata will not not have any effect on routing or swagger 1.2 spec generation and will be only used by the user of the library to store more information about the route.
=> Add metadata to Route

examples/restful-NCSA-logging.go, examples/restful-basic-authentication.go, examples/restful-form-handling.go, examples/restful-hello-world.go, examples/restful-html-template.go, examples/restful-multi-containers.go, examples/restful-no-cache-filter.go, examples/restful-path-tail.go, examples/restful-resource-functions.go, examples/restful-serve-static.go
In some examples `http.ListenAndServe(":8080", nil)` is used without `log.Fatal`, by doing so the program will exit with error status 1 when ListenAndServe fails as opposed to exiting with status 0.
=> Use log.Fatal consistently in all examples

entity_accessors_test.go, response.go, response_test.go
=> Expose http.Hijacker interface on Response

route.go, route_builder.go
This PR puts adds a Deprecated() method to the RouteBuilder.  The deprecated value in turn is set on the Route which go-restful-openapi can use to set the spec.Operation's Deprecated property which is then called out in the swagger UI.
Additional PR for go-restful-openapi will come as well to close the loop.
=> Add Deprecate method to RouteBuilder 

parameter.go, web_service.go
When used with `AllowMultiple(true)` this will trigger the swagger UI to build the appropriate entry component.  
For example:
An additional change is required in go-restful-openapi to populate the appropriate pieces.  I will send a PR for that if this gets merged.
=> Add CollectionFormat to Parameter type.  

entity_accessors.go, json.go, jsoniter.go, response_test.go
[json-iterator](https://github.com/json-iterator/go) is a high-performance 100% compatible drop-in replacement of "encoding/json". some go web framework already supported it, for example gin and iris etc.
use encoding/json as default json package but you can change to jsoniter by build from other tags
`go build -tags=jsoniter .`
for some api application,this is necessary.
=> add json-iterator for go-restful

container.go, route_builder.go, web_service.go
Folks that want these can configure them when preparing their logger (as we [already do in `log/log.go`'s `init`][1]).
[1]: https://github.com/emicklei/go-restful/blob/v2.8.0/log/log.go#L18
=> logging: Remove redundant [restful] prefixes

jsr311.go
This avoids suspicious re-assignment to a variable.
Signed-off-by: Iskander Sharipov <quasilyte@gmail.com>
=> simplify inputMediaOk var assignment

container.go, route.go
If set, the new route flag will override the compression setting used by the container. 
It solved the double-compression issue, or you can add auto compression just for specific routes.
=> #389 the route can now override the container.contentEncodingEnabled flag

curly.go, curly_route.go, jsr311.go, route.go
As part of performance evaluations in Kubernetes go-restful was a
significant source of time and more importantly memory allocations
during request processing. Profiling uncovered a number of places
where some specific changes could be made to avoid allocating which
reduces CPU use during garbage collection on per-request actions.
The following three changes were the smallest / easiest and should
be relatively easy to review. There are other hot spots that still
need to be investigated which may require more aggressive changes.
The use of new arrays for each phase of detectRoute can be simplified: each
pass filters the existing array and whatever is left at the end is
returned. While somewhat harder to read, this method is a significant 
source of allocations.
The mime handling methods …
=> Reduce allocations in per-request methods to improve performance

jsr311.go
In [JSR-311](https://download.oracle.com/otn-pub/jcp/jaxrs-1.0-fr-eval-oth-JSpec/jaxrs-1.0-final-spec.pdf?AuthParam=1553798515_382f64a715f97ddc0e38865c4e4f9b0f) there is this sentence:
> The media type of the request entity body (if any) is a supported input data format (see1section 3.5). If no methods support the media type of the request entity body an implemen-2tation MUST generate aWebApplicationExceptionwith an unsupported media type3response (HTTP 415 status) and no entity. The exception MUST be processed as described4in section 3.3.4.
The current implementation ignore the *if any* in parentheses, what happen is that if you make a `POST` request without body and without `Content-Type` header you receive a `415 - Unsupported Media Type`, but looking at the specification it say that …
=> Avoid return of 415 Unsupported Media Type when request body is empty

examples/restful-serve-static.go
missing log package, which contributes to a compile error
=> fix compile error for example/restful-serve-static.go

.gitignore, README.md, curly.go, curly_test.go, custom_verb.go, custom_verb_test.go, examples/restful-google-custom-method.go, go.mod, path_processor.go, path_processor_test.go, route.go, route_builder_test.go
support google [custome verb](https://cloud.google.com/apis/design/custom_methods)
resolve this issue. #394
=> feat: support google custome verb

path_processor.go, path_processor_test.go
In current implementation if you have a path parameter with some prefix or suffix the path processor doesn't extract the values correctly, see some examples:
```
/foo_{var}
/{var}_foo
/foo_{var}_bar
```
This patch handle those cases using regexp to correctly extract values.
=> handle path params with prefixes and suffixes

examples/restful-openapi.go, examples/restful-user-resource.go
There are breaking changes in go-openapi/spec#113.
This pull request fixes them.
```console
$ cd examples
$ go build restful-openapi.go
.\restful-openapi.go:157:5: cannot use promoted field ContactInfoProps.Name in struct literal of type spec.ContactInfo
.\restful-openapi.go:158:5: cannot use promoted field ContactInfoProps.Email in struct literal of type spec.ContactInfo
.\restful-openapi.go:159:5: cannot use promoted field ContactInfoProps.URL in struct literal of type spec.ContactInfo
.\restful-openapi.go:162:5: cannot use promoted field LicenseProps.Name in struct literal of type spec.License
.\restful-openapi.go:163:5: cannot use promoted field LicenseProps.URL in struct literal of type spec.License
```
=> Fix OpenAPI examples

route_builder.go
Fixes #419 
In the OpenAPI Specification, response object has a headers field. (https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#responseObject)
But there is no field about headers in struct ResponseError. So I can not use code to describe the response header.
```go
type ResponseError struct {
Code      int
Message   string
Model     interface{}
IsDefault bool
}
```
I added the Headers field with reference to the OpenAPI Specification. And in order to maintain compatibility, I did not modify Returns method, but added a new method ReturnsWithHeaders.
=> support describing response headers

container.go, jsr311.go, service_error.go, web_service_test.go
The relevant specification says that 405 Method Not Allowed responses
MUST list allowed mthods in the Allow header:
https://tools.ietf.org/html/rfc7231#section-6.5.5
https://tools.ietf.org/html/rfc7231#section-7.4.1
fixes #435
=> 405 Method Not Allowed must have Allow header

web_service.go
This PR fixes the remaining panic in `RemoveRoute()`.
=> Issue 471: Fix panic when removing a route that doesn't exist in w.routes.

README.md
This will fix the broken link on the README.md which points to the `UserResource` example.
=> Fix broken link to UserResource example

container.go, filter.go, parameter.go
Adds the following OpenAPI features to parameter:
- AllowEmptyValue
- Pattern
- Minimum
- Maximum
- MinLength
- MaxLength
- MinItems
- MaxItems
- UniqueItems
This also adds the operation name and route `ParameterDocs` to the `FilterChain` struct to allow filters access to both the operation name as well as the parameters defined for the requested route. Having this metadata allows filters to validate if a request is honoring the defined parameters.
This has additional changes to emicklei/go-restful-openapi#74 that would need to also be merged and released after this is.
=> feat(parameter): adds additional openapi mappings

container.go
The PR #478 brought some weird changes that breaks the filters behaviour.
We have a filter that creates another instance of Response to intercept all headers and data, then does an audit and modifies the data and only then it forwards to the original response.
But the lambda added in that PR breaks this logic, since the target function writes directly to the original response.
=> FilterChain should pass the request and response from filters to Target function

route.go
I was using an old version and saw that 
```
r.contentEncodingEnabled = &enabled
```
Fix was added, however String() should be updated to also use a pointer receiver.
Per Golang Docs "In general, all methods on a given type should have either value or pointer receivers, but not a mixture of both."
=> [Minor] Bad practice to have a mix of Receiver types.

web_service_test.go
With #520 clients receive different responses depending on a trailing slash in the requested path. This did not matter before, so this was a breaking change.
I wrote a small reproducer test to show the difference before and after 05c4911f7a613dab429b2cb4b9837e08c2709335.
Is this expected behavior? It breaks quite a lot of our stuff. 🙈
=> Add test for client request with and without trailing slash.
