emicklei/go-restful

container.go
Currently Conatiner's Handle() function does not take any container's filtering process, so I made filtering wrapper for this.
I think it must be provided for some situation such as using http.FileServer for authorized user.
=> change Container.Handle function to be filtered before handler process

route.go, web_service_test.go
=> Fix 415 HTTP errors for idempotent requests introduced in #170

swagger/model_builder.go
User "integer" for things of kind "uint64"
=> Use "string" for things of kind "string"

swagger/model_builder.go
Properly handle anonymous fields that are structs, by adding the model to the global model list.
=> Fix up support for anonymous fields.

container.go
Required for https://github.com/GoogleCloudPlatform/kubernetes/issues/6999
This is required to produce an appropriate response
=> Updating ServiceErrorHandleFunc to accept the request as well

response.go
I think this status must pass WriteHeader
=> Partial Content should pass

swagger/model_builder.go
This creates the following structure tags to control the model properties:
swagger%description -- string description
swagger%type -- string "type"  (e.g. "number")
swagger%enum -- string formatted array of enumeration values -- members separated by "|" characters
swagger%default -- string containing value of "defaultValue"
swagger%minimum, swagger%maximum -- what you think (string)
swagger%unique -- either "true" or "false" setting of uniqueItems
=> fixes #196 Set description property on model fields

container.go, container_test.go
Fixes https://github.com/emicklei/go-restful/issues/239
=> Fix HandleWithFilter receiver

swagger/swagger.go, swagger/swagger_builder.go, swagger/swagger_test.go, swagger/swagger_webservice.go, swagger/test_package/struct.go, swagger/utils_test.go
fixes #237, based on / includes #234 to use the json array diff fix
I created a new SwaggerBuilder that can evolve independently from the SwaggerService. We can eventually change the implementation such that SwaggerService uses SwaggerBuilder rather than the other way around, but this works for now.
=> Generate json

examples/google_app_engine/datastore/app.yaml, examples/google_app_engine/datastore/main.go, examples/google_app_engine/restful-user-service.go, log/log.go
resolve issue #247 and bring up-to-date with latest GAE APIs
=> #247 log not compatible with gae

compress.go
Hi,
having a defined container with enabled compression, it may occur an accidential situation when a Write operation is perfomed after a Close (compressor) operation. The result of such operation order (Write - Close - Write) is a nil ptr dereference and application "tango down" ;)
I've added the compressor presence check.
Best regards,
Marcin
=> Fix: nil pointer dereference when writing using closed compressor

examples/restful-curly-router_test.go
Adding a test so that next time we are able to catch issues like https://github.com/emicklei/go-restful/issues/272 sooner.
=> Adding a test for restful server

cors_filter.go, cors_filter_test.go
@emicklei ptal. I have a concern about the performance, I want to keep the regexp compile at most once. Hope to get your opinion.
=> cors filter support regex check against allowd origin

container.go, web_service.go
Locks should not be passed by value. see issue #299
=> Fix passing locks by value

swagger/swagger_test.go
=> Fix composeResponseMessages tests

examples/msgpack/msgpack_entity_test.go, examples/restful-curly-router_test.go, web_service.go
=> more replace fmt.Errorf with errors.New

examples/google_app_engine/restful-appstats-integration.go, examples/restful-filters.go, examples/restful-path-tail.go, swagger/model_builder_test.go, swagger/swagger_webservice.go
Formatting all files using gofmt.
=> gofmt fix on all *.go files

swagger/model_builder.go, swagger/model_builder_test.go
.. to show up in the Swagger spec
Change-Id: Icb200bc4d3b97e0234e89ef7c28a838ddc5f6cd2
=> excludes xml.Name attributes named "XMLName" 

examples/restful-user-resource.go
=> Change GET to POST for creation

container.go
Default router was changed to CurlyRouter as part of #306.
=> Update stale comment

examples/restful-basic-authentication.go
Golang has a BasicAuth method for HTTP Request. I use it instead of your method.
=> use golang internal http BasicAuth method

compressors.go, examples/google_app_engine/datastore/main.go, examples/google_app_engine/restful-user-service.go, examples/restful-swagger.go, examples/restful-user-resource.go, examples/restful-user-service.go, response.go, route.go, web_service.go
=> Fix commonly misspelled words

compressors.go, logger.go, route_builder.go
Fixes comments in a few places to keep go doc happy
=> Use proper formatting for comments to make go doc happy

CHANGES.md, jsr311.go, jsr311_test.go, route.go, route_builder.go
Sometimes you need to be able to say that a route only
applies under certain conditions. Now you can.
=> Add support for route condition functions

container.go, curly_test.go, jsr311.go, jsr311_test.go, path_expression.go, path_expression_test.go, path_processor.go, path_processor_test.go, route.go, route_test.go, router.go
=> Make JSR 311 routing and path param processing consistent

route.go, route_builder.go, route_builder_test.go
References emicklei/go-restful#392.
Requires https://github.com/emicklei/go-restful-openapi/pull/54 as well.
=> Fix issue with default responses and invalid status code 0.

route_builder.go, route_builder_test.go
New option added to Builder and tests for it.
=> Route Builder added option for contentEncodingEnabled

web_service.go
Easier to read incrementation.
=> Simplify code

CHANGES.md, container.go, container_test.go
Fix for using the request response from the resulting filter chain
=> Use request/response from filter chain result

bench_curly_test.go, bench_test.go
See https://github.com/golang/go/issues/32479
Fix #442.
Signed-off-by: Robert-André Mauchin <zebob.m@gmail.com>
=> Convert to string using rune()

jsr311.go, web_service_test.go
Becasue RFC7231 says we should.
fixes #434
=> List available representations in 406 body

web_service.go, web_service_test.go
add OPTIONS shortcut WebService receiver
https://github.com/emicklei/go-restful/issues/454
=> add options shortcut

doc.go
I've fixed issue:474. Can you merge my commit？
=> update doc.go #474

constants.go, response.go
I hope go-restful could support the content-type in application/zip,which implemented in download file usually.
=> Add MIME_ZIP

curly_test.go, path_processor_test.go, route.go, tracer_test.go
=> changed tokenizer to match std route match behavior; do not trimright… issue #497
